# YAML config for the application

# in dev mode, the default logged-in userid
default_user_id: john.doe

# number of posts that should be displayed per page
posts_per_page: 10
# number of 'most active posters' to display on the page
most_active_posters_on_page: 10
# number of 'most active posters' to display on the sidebox
most_active_posters_on_box: 5

# number of events that should be displayed per page
events_per_page: 10
# number of 'most active participants' to display on the page
most_active_participants_on_page: 10
# number of 'most active participants' to display on the sidebox
most_active_participants_on_box: 5

