# YAML config for the application

# in dev mode, the default logged-in userid
default_user_id: john.doe

# number of posts that should be displayed per page
posts_per_page: 10

# number of events that should be displayed per page
events_per_page: 10

